# This file is NOT generated by device/samsung/j2xlte/setup-makefiles.sh

LOCAL_PATH := vendor/samsung/j2xlte

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/bin/IPSecService:system/bin/IPSecService \
    $(LOCAL_PATH)/proprietary/bin/at_distributor:system/bin/at_distributor \
    $(LOCAL_PATH)/proprietary/bin/bih_config.sh:system/bin/bih_config.sh \
    $(LOCAL_PATH)/proprietary/bin/bootchecker:system/bin/bootchecker \
    $(LOCAL_PATH)/proprietary/bin/connfwexe:system/bin/connfwexe \
    $(LOCAL_PATH)/proprietary/bin/ddexe:system/bin/ddexe \
    $(LOCAL_PATH)/proprietary/bin/ext_data.sh:system/bin/ext_data.sh \
    $(LOCAL_PATH)/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh \
    $(LOCAL_PATH)/proprietary/bin/ext_symlink.sh:system/bin/ext_symlink.sh \
    $(LOCAL_PATH)/proprietary/bin/inputfreq.sh:system/bin/inputfreq.sh \
    $(LOCAL_PATH)/proprietary/bin/macloader:system/bin/macloader \
    $(LOCAL_PATH)/proprietary/bin/mfgloader:system/bin/mfgloader \
    $(LOCAL_PATH)/proprietary/bin/modemd:system/bin/modemd \
    $(LOCAL_PATH)/proprietary/bin/recoveryfreq.sh:system/bin/recoveryfreq.sh \
    $(LOCAL_PATH)/proprietary/bin/scs:system/bin/scs \
    $(LOCAL_PATH)/proprietary/bin/smdexe:system/bin/smdexe \
    $(LOCAL_PATH)/proprietary/bin/sprdSleepLog:system/bin/sprdSleepLog \
    $(LOCAL_PATH)/proprietary/bin/wlandutservice:system/bin/wlandutservice \
    $(LOCAL_PATH)/proprietary/bin/gpsd:system/bin/gpsd 

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/etc/.omxregister:system/etc/.omxregister \
    $(LOCAL_PATH)/proprietary/etc/connectivity_calibration.ini:system/etc/connectivity_calibration.ini \
    $(LOCAL_PATH)/proprietary/etc/connectivity_configure.ini:system/etc/connectivity_configure.ini \
    $(LOCAL_PATH)/proprietary/etc/feature_default.xml:system/etc/feature_default.xml \
    $(LOCAL_PATH)/proprietary/etc/firmware/sc2331_fdl.bin:system/etc/firmware/sc2331_fdl.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/sc2331_fw.bin:system/etc/firmware/sc2331_fw.bin \
    $(LOCAL_PATH)/proprietary/etc/floating_feature.xml:system/etc/floating_feature.xml \
    $(LOCAL_PATH)/proprietary/etc/nwk_info.xml:system/etc/nwk_info.xml \
    $(LOCAL_PATH)/proprietary/etc/plmn_delta.bin:system/etc/plmn_delta.bin \
    $(LOCAL_PATH)/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    $(LOCAL_PATH)/proprietary/etc/purenandpackages.txt:system/etc/purenandpackages.txt \
    $(LOCAL_PATH)/proprietary/etc/purenandpackages_pref.txt:system/etc/purenandpackages_pref.txt \
    $(LOCAL_PATH)/proprietary/etc/somxreg.conf:system/etc/somxreg.conf \
    $(LOCAL_PATH)/proprietary/etc/spn-conf.xml:system/etc/spn-conf.xml \
    $(LOCAL_PATH)/proprietary/etc/thermalSensorsConfig.xml:system/etc/thermalSensorsConfig.xml 
    $(LOCAL_PATH)/proprietary/etc/gps.xml:system/etc/gps.xml \
    $(LOCAL_PATH)/proprietary/etc/gps.cer:system/bin/gps.cer

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    $(LOCAL_PATH)/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    $(LOCAL_PATH)/proprietary/lib/libSamsungMusic_v5.so:system/lib/libSamsungMusic_v5.so \
    $(LOCAL_PATH)/proprietary/lib/libSamsungPreProcess.so:system/lib/libSamsungPreProcess.so \
    $(LOCAL_PATH)/proprietary/lib/libSoundAlive_VSP_ver315b_arm.so:system/lib/libSoundAlive_VSP_ver315b_arm.so \
    $(LOCAL_PATH)/proprietary/lib/lib_DNSe_EP_ver216c.so:system/lib/lib_DNSe_EP_ver216c.so \
    $(LOCAL_PATH)/proprietary/lib/lib_SA_GoogleFX_ver119k.so:system/lib/lib_SA_GoogleFX_ver119k.so \
    $(LOCAL_PATH)/proprietary/lib/lib_SamsungRec_V04013.so:system/lib/lib_SamsungRec_V04013.so \
    $(LOCAL_PATH)/proprietary/lib/lib_Samsung_AudioZoom_v102.so:system/lib/lib_Samsung_AudioZoom_v102.so \
    $(LOCAL_PATH)/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    $(LOCAL_PATH)/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03008.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03008.so \
    $(LOCAL_PATH)/proprietary/lib/lib_SoundAlive_3DPosition_ver107.so:system/lib/lib_SoundAlive_3DPosition_ver107.so \
    $(LOCAL_PATH)/proprietary/lib/lib_SoundAlive_SRC192_ver205.so:system/lib/lib_SoundAlive_SRC192_ver205.so \
    $(LOCAL_PATH)/proprietary/lib/lib_SoundAlive_play_plus_ver126a.so:system/lib/lib_SoundAlive_play_plus_ver126a.so \
    $(LOCAL_PATH)/proprietary/lib/lib_SoundAlive_ver118t.so:system/lib/lib_SoundAlive_ver118t.so \
    $(LOCAL_PATH)/proprietary/lib/lib_soundaliveresampler.so:system/lib/lib_soundaliveresampler.so \
    $(LOCAL_PATH)/proprietary/lib/libaccauthentication_jni.so:system/lib/libaccauthentication_jni.so \
    $(LOCAL_PATH)/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    $(LOCAL_PATH)/proprietary/lib/libaudiosa.so:system/lib/libaudiosa.so \
    $(LOCAL_PATH)/proprietary/lib/libboost.so:system/lib/libboost.so \
    $(LOCAL_PATH)/proprietary/lib/libcordon.so:system/lib/libcordon.so \
    $(LOCAL_PATH)/proprietary/lib/libengmode.so:system/lib/libengmode.so \
    $(LOCAL_PATH)/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    $(LOCAL_PATH)/proprietary/lib/libmysound.so:system/lib/libmysound.so \
    $(LOCAL_PATH)/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    $(LOCAL_PATH)/proprietary/lib/libsAMRNB.so:system/lib/libsAMRNB.so \
    $(LOCAL_PATH)/proprietary/lib/libsAMRWB.so:system/lib/libsAMRWB.so \
    $(LOCAL_PATH)/proprietary/lib/libsaiv_codec.so:system/lib/libsaiv_codec.so \
    $(LOCAL_PATH)/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    $(LOCAL_PATH)/proprietary/lib/libsamsungRecord_zoom.so:system/lib/libsamsungRecord_zoom.so \
    $(LOCAL_PATH)/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    $(LOCAL_PATH)/proprietary/lib/libsamsungearcare.so:system/lib/libsamsungearcare.so \
    $(LOCAL_PATH)/proprietary/lib/libsamsungeffect.so:system/lib/libsamsungeffect.so \
    $(LOCAL_PATH)/proprietary/lib/libsamsungpowersound.so:system/lib/libsamsungpowersound.so \
    $(LOCAL_PATH)/proprietary/lib/libsdp_crypto.so:system/lib/libsdp_crypto.so \
    $(LOCAL_PATH)/proprietary/lib/libsec_devenc.so:system/lib/libsec_devenc.so \
    $(LOCAL_PATH)/proprietary/lib/libsetproperty.so:system/lib/libsetproperty.so \
    $(LOCAL_PATH)/proprietary/lib/libsfextaac.so:system/lib/libsfextaac.so \
    $(LOCAL_PATH)/proprietary/lib/libsfextavi.so:system/lib/libsfextavi.so \
    $(LOCAL_PATH)/proprietary/lib/libsfextcmn.so:system/lib/libsfextcmn.so \
    $(LOCAL_PATH)/proprietary/lib/libsfextcp.so:system/lib/libsfextcp.so \
    $(LOCAL_PATH)/proprietary/lib/libsfextflac.so:system/lib/libsfextflac.so \
    $(LOCAL_PATH)/proprietary/lib/libsfextflv.so:system/lib/libsfextflv.so \
    $(LOCAL_PATH)/proprietary/lib/libsfextmkv.so:system/lib/libsfextmkv.so \
    $(LOCAL_PATH)/proprietary/lib/libsfextmp4f.so:system/lib/libsfextmp4f.so \
    $(LOCAL_PATH)/proprietary/lib/libsfextrmf.so:system/lib/libsfextrmf.so \
    $(LOCAL_PATH)/proprietary/lib/libsfextwmf.so:system/lib/libsfextwmf.so \
    $(LOCAL_PATH)/proprietary/lib/libshdace.so:system/lib/libshdace.so \
    $(LOCAL_PATH)/proprietary/lib/libsimageis_jni.so:system/lib/libsimageis_jni.so \
    $(LOCAL_PATH)/proprietary/lib/libsomp.so:system/lib/libsomp.so \
    $(LOCAL_PATH)/proprietary/lib/libsoundalive.so:system/lib/libsoundalive.so \
    $(LOCAL_PATH)/proprietary/lib/libsoundspeed.so:system/lib/libsoundspeed.so \
    $(LOCAL_PATH)/proprietary/lib/libspdkeygen.so:system/lib/libspdkeygen.so \
    $(LOCAL_PATH)/proprietary/lib/libsprdftms.so:system/lib/libsprdftms.so \
    $(LOCAL_PATH)/proprietary/lib/libvariablespeed.so:system/lib/libvariablespeed.so \
    $(LOCAL_PATH)/proprietary/lib/libvtmanager.so:system/lib/libvtmanager.so \
    $(LOCAL_PATH)/proprietary/lib/libvtstack.so:system/lib/libvtstack.so \
    $(LOCAL_PATH)/libwrappergps.so:system/lib/libwrappergps.so \
    $(LOCAL_PATH)/proprietary/lib/modules/pskey_bt.txt:system/lib/modules/pskey_bt.txt \
    $(LOCAL_PATH)/proprietary/lib/soundfx/libaudioeffectoffload.so:system/lib/soundfx/libaudioeffectoffload.so \
    $(LOCAL_PATH)/proprietary/lib/soundfx/libaudiosa_sec.so:system/lib/soundfx/libaudiosa_sec.so \
    $(LOCAL_PATH)/proprietary/lib/soundfx/libmyspace.so:system/lib/soundfx/libmyspace.so
    
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/vendor/firmware/vbc_eq:system/vendor/firmware/vbc_eq \
    $(LOCAL_PATH)/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    $(LOCAL_PATH)/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/keylayout/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \
    $(LOCAL_PATH)/proprietary/keylayout/headset-keyboard.kl:system/usr/keylayout/headset-keyboard.kl \
    $(LOCAL_PATH)/proprietary/keylayout/sci-keypad.kl:system/usr/keylayout/sci-keypad.kl \
    $(LOCAL_PATH)/proprietary/keylayout/sec_touchkey.kl:system/usr/keylayout/sec_touchkey.kl \
    $(LOCAL_PATH)/proprietary/keylayout/sprd-eic-keys.kl:system/usr/keylayout/sprd-eic-keys.kl \
    $(LOCAL_PATH)/proprietary/keylayout/sprd-gpio-keys.kl:system/usr/keylayout/sprd-gpio-keys.kl \
    $(LOCAL_PATH)/proprietary/keylayout/Synaptics_RMI4_TouchPad_Sensor.idc:system/usr/idc/Synaptics_RMI4_TouchPad_Sensor.idc \
    $(LOCAL_PATH)/proprietary/keylayout/Synaptics_HID_TouchPad.idc:system/usr/idc/Synaptics_HID_TouchPad.idc
